name: Java CI with test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Check out the code from the repository

    - name: Check Ubuntu version
      run: lsb_release -a || cat /etc/os-release

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up a Python environment
      with:
        python-version: '3.9'  # Specify the Python version
