name: Java CI with test

on:
  push:
    branches: [ "vp-rem" ]  # Run the workflow on every push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Check out the code from the repository

    - name: Set up JDK 11
      uses: actions/setup-java@v3  # Set up Java environment
      with:
        java-version: '11'
